apiVersion: v1
kind: Service
metadata:
  name: prometheus-custom-metrics-in-k8s
spec:
  selector:
    app: prometheus-custom-metrics-in-k8s
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: NodePort