apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: prometheus-custom-metrics-in-k8s-monitor
  namespace: monitoring
spec:
  namespaceSelector:
    matchNames:
      - default # namespace where the target service is running
  selector:
    matchLabels:
      app: prometheus-custom-metrics-in-k8s
  endpoints:
    - port: metrics
      path: /metrics
      interval: 10s